services:
  - type: web
    name: lr1-parser-1
    env: python
    buildCommand: |
      apt-get update && apt-get install -y graphviz
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
